#include<stdio.h>
#include<stdlib.h>
#include<time.h>
#include<iostream>
	int main(void){
		int num,used[10]={0},magic[4],count=0,i=0,imput[5],A=0,B=0,c=0,x=0,garbage=0;
		char play='y',a,b;
		while(play='y'){
			int num,used[10]={0},magic[4],count=0,i=0,imput[5],A=0,B=0,c=0,x=0,garbage=0;
			char play='y',a,b;
			time_t now;
			time(&now);
			printf("現在時間%s\n",asctime(localtime(&now)));
			srand(time(NULL));
			while(count!=4&&c==0){
				num=(rand()%10);
				if(used[num]==0){
					magic[count]=num;
					//printf("%d",magic[count]);
					count++;
					used[num]=1;				
				}
			}
			while(1){
				printf("請輸入一四位數字:\n");
				//system("pause");
				//garbage=0;
				while(1){
					a=getchar();
					if(a=='\n'&&garbage==0){
						if(imput[0]==imput[1]||imput[0]==imput[2]||imput[0]==imput[3]||imput[1]==imput[2]||imput[1]==imput[3]||imput[2]==imput[3]||i!=4){
						garbage++;
						//printf("wrong\n");
						//printf("%d\n",a);
							break;
						}
					break;
					}
					if((a<='9'&&a>='0')||a=='\n'){
						if(a<='9'&&a>='0'){
						imput[c]=a;
						c++;
						i++;
						}
					}
					else{
						//printf("wrong\n");
						//printf("%d",a);
						garbage++;
					}
					if(garbage==1){
						break;
					}
				}
				if(garbage==0){
					if(imput[0]==magic[0]+48){
						A++;
					}
					if(imput[1]==magic[1]+48){
						A++;
					}
					if(imput[2]==magic[2]+48){
						A++;
					}
					if(imput[3]==magic[3]+48){
						A++;
					}
					if(imput[0]==magic[1]+48){
						B++;
					}
					if(imput[0]==magic[2]+48){
						B++;
					}
					if(imput[0]==magic[3]+48){
						B++;
					}
					if(imput[1]==magic[0]+48){
						B++;
					}
					if(imput[1]==magic[2]+48){
						B++;
					}
					if(imput[1]==magic[3]+48){
						B++;
					}
					if(imput[2]==magic[0]+48){
						B++;
					}
					if(imput[2]==magic[1]+48){
						B++;
					}
					if(imput[2]==magic[3]+48){
						B++;
					}
					if(imput[3]==magic[0]+48){
						B++;
					}
					if(imput[3]==magic[1]+48){
						B++;
					}
					if(imput[3]==magic[2]+48){
						B++;
					}
					i=0;
					c=0;
					printf("%dA%dB\n",A,B);
					x++;
					if(A==4){	
						break;
					}
					else{
						printf("猜錯%d次\n",x);
					}
					A=0;
					B=0;
					count=0;	
				}
				if(garbage==1){
					while(a!='\n'){
						a=getchar();
					}
				}
				i=0;
				c=0;
				garbage=0;
				continue;
			}
			printf("play again?(y/n)\n");
			play=getchar();
			if(play=='n'){
				system("pause");
                return 0;
			}
			//printf("%c%c%c%c",imput[4]);
			//system("pause");
			play='y';
		}	 
	}
